import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import SideBar from "./components/SideBar";
import Hydration from "@/store/Hydration";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat-ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Providers>
       
          <div className="flex h-screen">
            {/* Sidebar Desktop */}
            <div className="hidden md:block">
              <SideBar className="w-64 h-full" />
            </div>

            {/* Sidebar Mobile */}
            <div className="md:hidden">
              <SideBar className="fixed inset-y-0 left-0 z-40 w-64" />
            </div>

            {/* Main Chat Area */}
            <main className="flex-1 h-full overflow-y-auto">
              {children}
            </main>
          </div>
        
        </Providers>

      </body>
    </html>
  );
}
