import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ThemeProvider } from "./components/theme-provider";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import ModeToggle from "./components/modeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat-ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <SidebarProvider>
              <div className="flex w-full h-screen text-gray-700 hover:text-blue-600 dark:text-gray-300 dark:hover:text-blue-400">
                <AppSidebar />

                <main className="flex-1 flex flex-col h-full w-full ">
                  <div className="flex items-center justify-between bg-[#F8F3FC] p-2 border-b border-gray-200">
                    <SidebarTrigger />
                    <ModeToggle />
                  </div>
                  {children}
                </main>
              </div>
            </SidebarProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
